### ISSUE TITLE
How to generate a class relationship diagram

### ISSUE THREAD

**Issue by xareelee** [manusimidt/xbrl_parser#12]
Actually, it's not a bug report.

I just wonder what tool do you use to generate this image:

![](https://github.com/manusimidt/xbrl_parser/blob/main/docs/img/parser_class_diagram.png?raw=true)

**Comment by manusimidt** [comment]
@xareelee 
I used [draw.io / diagrams.net](https://www.diagrams.net/).

Can only recommend it :) They also have a desktop application. But their online version is also very stable and fast.

**Comment by xareelee** [comment]
Thanks for reply.

Is it generated by analyzing the code automatically, or by drawing this pic manually?

**Comment by manusimidt** [comment]
@xareelee 
No, unfortunately you have to draw it manually. 

But i also think generating a diagram from python code is really hard, since python has weak types. Hence the diagram tool can not know for sure which type a member of a class has.

If you find a tool that works let me know 😆
