### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by mrx23dot** [manusimidt/xbrl_parser#32]
How to use parse_instance? Please update example.

```
xbrlParser = XbrlParser(cache)
xbrl_url = 'https://www.sec.gov/Archives/edgar/data/789019/000156459017014900/msft-20170630.xml'
inst: XbrlInstance = XbrlParser.parse_instance(xbrl_url)
```

  File "C:\tmp\SECgov\parse_sec.py", line 18, in <module>
    inst: XbrlInstance = XbrlParser.parse_instance(xbrl_url)
TypeError: parse_instance() missing 1 required positional argument: 'url'

```
xbrlParser = XbrlParser(cache)
xbrl_url = 'https://www.sec.gov/Archives/edgar/data/789019/000156459017014900/msft-20170630.xml'
inst: XbrlInstance = XbrlParser.parse_instance(url=xbrl_url)
```
  File "C:\tmp\SECgov\parse_sec.py", line 18, in <module>
    inst: XbrlInstance = XbrlParser.parse_instance(url=xbrl_url)
TypeError: parse_instance() missing 1 required positional argument: 'self'

**Comment by manusimidt** [comment]
@mrx23dot Thank you for filing the issue.
Was a capitalization error.
change 
```python
inst: XbrlInstance = XbrlParser.parse_instance(url=xbrl_url)
```
to
```python
inst: XbrlInstance = xbrlParser.parse_instance(url=xbrl_url)
```

**Comment by mrx23dot** [comment]
Thank you!
