### ISSUE TITLE
Currency extraction

### ISSUE THREAD

**Issue by mrx23dot** [manusimidt/xbrl_parser#41]
Any chance we could extract the reportedCurrency e.g: "USD", it's in the high level xbrli header.

`<xbrli:measure>iso4217:USD</xbrli:measure>`

in https://www.sec.gov/ix?doc=/Archives/edgar/data/0000320193/000032019321000056/aapl-20210327.htm

It's also in xml:
```
<xbrli:unit id="USD">
<xbrli:measure>iso4217:USD</xbrli:measure>
</xbrli:unit>
```
https://www.sec.gov/Archives/edgar/data/1403570/000149315221006582/qtmm-20190630.xml

**Comment by manusimidt** [comment]
Unfortunately I am not entirely sure what you mean.
The XbrlInstance object instance has a dictionary called unit_map which stores each unit with the corresponding id in the dictionary.
![image](https://user-images.githubusercontent.com/29599104/124467705-7f926480-dd98-11eb-822d-9ad6a2fbdd83.png)

The parser also automatically links the units to the facts:
![image](https://user-images.githubusercontent.com/29599104/124467827-a94b8b80-dd98-11eb-8421-9d084f14e3ce.png)

The code I used:
```xml
cache: HttpCache = HttpCache('./cache')
xbrlParser = XbrlParser(cache)

xbrl_url = 'https://www.sec.gov/Archives/edgar/data/0000320193/000032019321000056/aapl-20210327.htm'

inst: XbrlInstance = xbrlParser.parse_instance(xbrl_url)
print(inst.unit_map)
print([str(fact.unit) for fact in inst.facts if fact.concept.name == 'Assets'])
```

**Comment by mrx23dot** [comment]
Works great, thanks!
